### ISSUE TITLE
npm start throws error

### ISSUE THREAD

**Issue by mesnia** [HarrKxx/eleos#10]
# ## npm start throws error

## OS: **Ubuntu running in Windows Subsystem for Linux**

1. Was able to install without any errors by following the instruction.
2. It throws below error after firing `npm start`

```
> Eleos@0.0.6 start /home/mesnia/Builds/eleos
> electron .

/home/mesnia/Builds/eleos/node_modules/electron/dist/electron: error while loading shared libraries: libgconf-2 .so.4: cannot open shared object file: No such file or directory
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! Eleos@0.0.6 start: `electron .`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the Eleos@0.0.6 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     **/home/mesnia/.npm/_logs/2018-01-04T01_39_33_984Z-debug.log**
```
Content of /home/mesnia/.npm/_logs/2018-01-04T01_39_33_984Z-debug.log is 
```

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@5.5.1
3 info using node@v9.3.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle Eleos@0.0.6~prestart: Eleos@0.0.6
6 info lifecycle Eleos@0.0.6~start: Eleos@0.0.6
7 verbose lifecycle Eleos@0.0.6~start: unsafe-perm in lifecycle true
8 verbose lifecycle Eleos@0.0.6~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/mesnia/Builds/eleos/node_modules/.bin:/home/mesnia/bin:/home/mesnia/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
9 verbose lifecycle Eleos@0.0.6~start: CWD: /home/mesnia/Builds/eleos
10 silly lifecycle Eleos@0.0.6~start: Args: [ '-c', 'electron .' ]
11 info lifecycle Eleos@0.0.6~start: Failed to exec start script
12 verbose stack Error: Eleos@0.0.6 start: `electron .`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:159:13)
12 verbose stack     at maybeClose (internal/child_process.js:943:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
13 verbose pkgid Eleos@0.0.6
14 verbose cwd /home/mesnia/Builds/eleos
15 verbose Linux 4.4.0-43-Microsoft
16 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
17 verbose node v9.3.0
18 verbose npm  v5.5.1
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error Eleos@0.0.6 start: `electron .`
23 error spawn ENOENT
24 error Failed at the Eleos@0.0.6 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by HarrKxx** [comment]
Hello,

You have a wrong version, should be 0.0.9 not 0.0.6
